const topicData = [
  {
    topic: "DSA",
    task_name: "Reverse a Linked List",
    leetcode_link: "https://leetcode.com/problems/reverse-linked-list/",
    yt_link: "https://www.youtube.com/watch?v=D7y_hoT_P4Q",
    article_link: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
    level: "medium",
  },
  {
    topic: "DSA",
    task_name: "Binary Search Implementation",
    leetcode_link: "https://leetcode.com/problems/binary-search/",
    yt_link: "https://www.youtube.com/watch?v=P3YID7liBug",
    article_link: "https://www.programiz.com/dsa/binary-search",
    level: "easy",
  },
  {
    topic: "DSA",
    task_name: "Merge Two Sorted Lists",
    leetcode_link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    yt_link: "https://www.youtube.com/watch?v=XIdigk956u0",
    article_link:
      "https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/",
    level: "medium",
  },
  {
    topic: "DSA",
    task_name: "Find Cycle in Linked List",
    leetcode_link: "https://leetcode.com/problems/linked-list-cycle/",
    yt_link: "https://www.youtube.com/watch?v=354J83hX7LA",
    article_link: "https://www.geeksforgeeks.org/detect-loop-linked-list/",
    level: "medium",
  },
  {
    topic: "DSA",
    task_name: "Implement Stack using Queues",
    leetcode_link:
      "https://leetcode.com/problems/implement-stack-using-queues/",
    yt_link: "https://www.youtube.com/watch?v=rW4vm0-DLYc",
    article_link: "https://www.geeksforgeeks.org/implement-stack-using-queue/",
    level: "hard",
  },
  {
    topic: "Database",
    task_name: "Write SQL Query for Joins",
    leetcode_link: "https://leetcode.com/problems/combine-two-tables/",
    yt_link: "https://www.youtube.com/watch?v=9yeOJ0ZMUYw",
    article_link: "https://www.w3schools.com/sql/sql_join.asp",
    level: "medium",
  },
  {
    topic: "Database",
    task_name: "Design a Database Schema",
    leetcode_link: "https://leetcode.com/problems/design-a-database/",
    yt_link: "https://www.youtube.com/watch?v=ztHopE5Wnpc",
    article_link: "https://www.geeksforgeeks.org/database-design-in-dbms/",
    level: "hard",
  },
  {
    topic: "Database",
    task_name: "Optimize SQL Query",
    leetcode_link: "https://leetcode.com/problems/optimize-sql-query/",
    yt_link: "https://www.youtube.com/watch?v=2W1L1OjsnRs",
    article_link: "https://www.sqlshack.com/sql-query-optimization/",
    level: "hard",
  },
  {
    topic: "Database",
    task_name: "Indexing in Databases",
    leetcode_link: "https://leetcode.com/problems/database-indexing/",
    yt_link: "https://www.youtube.com/watch?v=HubezKbFL7E",
    article_link: "https://www.geeksforgeeks.org/indexing-in-databases/",
    level: "medium",
  },
  {
    topic: "Database",
    task_name: "Normalization Basics",
    leetcode_link: "https://leetcode.com/problems/database-normalization/",
    yt_link: "https://www.youtube.com/watch?v=UrYLYy7WSHM",
    article_link:
      "https://www.studytonight.com/dbms/database-normalization.php",
    level: "easy",
  },
  {
    topic: "Machine Learning",
    task_name: "Linear Regression Implementation",
    leetcode_link: "https://leetcode.com/problems/linear-regression/",
    yt_link: "https://www.youtube.com/watch?v=E5RjzSK0fvY",
    article_link:
      "https://www.geeksforgeeks.org/linear-regression-python-implementation/",
    level: "medium",
  },
  {
    topic: "Machine Learning",
    task_name: "K-Means Clustering",
    leetcode_link: "https://leetcode.com/problems/k-means-clustering/",
    yt_link: "https://www.youtube.com/watch?v=4b5d3muPQmA",
    article_link:
      "https://www.analyticsvidhya.com/blog/2019/08/k-means-clustering/",
    level: "medium",
  },
  {
    topic: "Machine Learning",
    task_name: "Decision Tree Basics",
    leetcode_link: "https://leetcode.com/problems/decision-tree/",
    yt_link: "https://www.youtube.com/watch?v=7VeUPuFGJHk",
    article_link:
      "https://www.geeksforgeeks.org/decision-tree-introduction-example/",
    level: "easy",
  },
  {
    topic: "Machine Learning",
    task_name: "Neural Network Basics",
    leetcode_link: "https://leetcode.com/problems/neural-network/",
    yt_link: "https://www.youtube.com/watch?v=aircAruvnKk",
    article_link: "https://towardsdatascience.com/neural-networks-explained/",
    level: "hard",
  },
  {
    topic: "Machine Learning",
    task_name: "Overfitting Prevention",
    leetcode_link: "https://leetcode.com/problems/overfitting-prevention/",
    yt_link: "https://www.youtube.com/watch?v=9Y3yaoi9i5E",
    article_link:
      "https://machinelearningmastery.com/overfitting-machine-learning-models/",
    level: "hard",
  },
  {
    topic: "Operating System",
    task_name: "Process Scheduling Algorithms",
    leetcode_link: "https://leetcode.com/problems/process-scheduling/",
    yt_link: "https://www.youtube.com/watch?v=5IF4cnjCi0g",
    article_link:
      "https://www.geeksforgeeks.org/cpu-scheduling-in-operating-systems/",
    level: "medium",
  },
  {
    topic: "Operating System",
    task_name: "Deadlock Detection",
    leetcode_link: "https://leetcode.com/problems/deadlock-detection/",
    yt_link: "https://www.youtube.com/watch?v=2xflhG0c7Yw",
    article_link: "https://www.geeksforgeeks.org/deadlock-detection-recovery/",
    level: "hard",
  },
  {
    topic: "Operating System",
    task_name: "Memory Management Basics",
    leetcode_link: "https://leetcode.com/problems/memory-management/",
    yt_link: "https://www.youtube.com/watch?v=2kyHWIh9MQE",
    article_link:
      "https://www.tutorialspoint.com/operating_system/os_memory_management.htm",
    level: "medium",
  },
  {
    topic: "Operating System",
    task_name: "File System Implementation",
    leetcode_link: "https://leetcode.com/problems/file-system/",
    yt_link: "https://www.youtube.com/watch?v=5t0sD6a2bcU",
    article_link: "https://www.geeksforgeeks.org/file-system-implementation/",
    level: "hard",
  },
  {
    topic: "Operating System",
    task_name: "Thread Synchronization",
    leetcode_link: "https://leetcode.com/problems/thread-synchronization/",
    yt_link: "https://www.youtube.com/watch?v=71lpKHgBkxc",
    article_link: "https://www.geeksforgeeks.org/synchronization-in-os/",
    level: "medium",
  },
  {
    topic: "Algorithms",
    task_name: "Dijkstra’s Algorithm",
    leetcode_link: "https://leetcode.com/problems/shortest-path-dijkstra/",
    yt_link: "https://www.youtube.com/watch?v=bZkzH5x0Y0c",
    article_link:
      "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm/",
    level: "hard",
  },
  {
    topic: "Algorithms",
    task_name: "Quick Sort Implementation",
    leetcode_link: "https://leetcode.com/problems/sort-an-array/",
    yt_link: "https://www.youtube.com/watch?v=Hoixgm4-P4M",
    article_link: "https://www.programiz.com/dsa/quick-sort",
    level: "medium",
  },
  {
    topic: "Algorithms",
    task_name: "Knapsack Problem",
    leetcode_link: "https://leetcode.com/problems/knapsack-problem/",
    yt_link: "https://www.youtube.com/watch?v=8LusJS5-AGo",
    article_link: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
    level: "hard",
  },
  {
    topic: "Algorithms",
    task_name: "Binary Tree Traversal",
    leetcode_link:
      "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    yt_link: "https://www.youtube.com/watch?v=g_sYu6K0v-0",
    article_link:
      "https://www.geeksforgeeks.org/tree-traversals-inorder-preorder-and-postorder/",
    level: "medium",
  },
  {
    topic: "Algorithms",
    task_name: "Depth First Search",
    leetcode_link: "https://leetcode.com/problems/dfs-graph/",
    yt_link: "https://www.youtube.com/watch?v=Urx87-NMm6c",
    article_link:
      "https://www.geeksforgeeks.org/depth-first-search-or-dfs-for-a-graph/",
    level: "medium",
  },
  {
    topic: "Networking",
    task_name: "TCP/IP Basics",
    leetcode_link: "https://leetcode.com/problems/tcp-ip/",
    yt_link: "https://www.youtube.com/watch?v=RF7v0OhyhUw",
    article_link: "https://www.geeksforgeeks.org/tcp-ip-model/",
    level: "easy",
  },
  {
    topic: "Networking",
    task_name: "Subnetting Practice",
    leetcode_link: "https://leetcode.com/problems/subnetting/",
    yt_link: "https://www.youtube.com/watch?v=5WUm3sDHE6s",
    article_link:
      "https://www.tutorialspoint.com/subnetting-in-computer-networks",
    level: "medium",
  },
  {
    topic: "Networking",
    task_name: "DNS Resolution Process",
    leetcode_link: "https://leetcode.com/problems/dns-resolution/",
    yt_link: "https://www.youtube.com/watch?v=mpQZVYPurLA",
    article_link: "https://www.cloudflare.com/learning/dns/how-dns-works/",
    level: "medium",
  },
  {
    topic: "Networking",
    task_name: "OSI Model Layers",
    leetcode_link: "https://leetcode.com/problems/osi-model/",
    yt_link: "https://www.youtube.com/watch?v=3bH2S3kZJo",
    article_link: "https://www.geeksforgeeks.org/layers-of-osi-model/",
    level: "easy",
  },
  {
    topic: "Networking",
    task_name: "Packet Analysis",
    leetcode_link: "https://leetcode.com/problems/packet-analysis/",
    yt_link: "https://www.youtube.com/watch?v=5W5A6iY2b9w",
    article_link:
      "https://www.wireshark.org/docs/wsug_html_chunked/ChWorkIntro.html",
    level: "hard",
  },
  {
    topic: "Software Engineering",
    task_name: "Agile Methodology Basics",
    leetcode_link: "https://leetcode.com/problems/agile-methodology/",
    yt_link: "https://www.youtube.com/watch?v=Z9QbYZh1Y6A",
    article_link: "https://www.agilealliance.org/agile101/",
    level: "easy",
  },
  {
    topic: "Software Engineering",
    task_name: "Design Patterns Overview",
    leetcode_link: "https://leetcode.com/problems/design-patterns/",
    yt_link: "https://www.youtube.com/watch?v=v9ejT8k9Z8E",
    article_link: "https://refactoring.guru/design-patterns",
    level: "medium",
  },
  {
    topic: "Software Engineering",
    task_name: "Unit Testing Basics",
    leetcode_link: "https://leetcode.com/problems/unit-testing/",
    yt_link: "https://www.youtube.com/watch?v=3kzHmaeozDI",
    article_link:
      "https://www.geeksforgeeks.org/unit-testing-software-testing/",
    level: "medium",
  },
  {
    topic: "Software Engineering",
    task_name: "CI/CD Pipeline Setup",
    leetcode_link: "https://leetcode.com/problems/ci-cd-pipeline/",
    yt_link: "https://www.youtube.com/watch?v=scEDHsr3APg",
    article_link:
      "https://www.atlassian.com/continuous-delivery/ci-cd-pipeline",
    level: "hard",
  },
  {
    topic: "Software Engineering",
    task_name: "Code Review Best Practices",
    leetcode_link: "https://leetcode.com/problems/code-review/",
    yt_link: "https://www.youtube.com/watch?v=6TK6S4aD2qY",
    article_link:
      "https://smartbear.com/learn/code-review/best-practices-for-code-review/",
    level: "medium",
  },
  {
    topic: "Web Development",
    task_name: "Build a Responsive Navbar",
    leetcode_link: "https://leetcode.com/problems/responsive-navbar/",
    yt_link: "https://www.youtube.com/watch?v=At4B7A4GOPg",
    article_link: "https://www.w3schools.com/css/css_navbar.asp",
    level: "medium",
  },
  {
    topic: "Web Development",
    task_name: "REST API Integration",
    leetcode_link: "https://leetcode.com/problems/rest-api/",
    yt_link: "https://www.youtube.com/watch?v=7YcW25PHnAA",
    article_link:
      "https://www.smashingmagazine.com/2018/01/understanding-using-rest-api/",
    level: "hard",
  },
  {
    topic: "Web Development",
    task_name: "CSS Flexbox Layout",
    leetcode_link: "https://leetcode.com/problems/css-flexbox/",
    yt_link: "https://www.youtube.com/watch?v=phWxA89Dy94",
    article_link: "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
    level: "medium",
  },
  {
    topic: "Web Development",
    task_name: "JavaScript Event Handling",
    leetcode_link: "https://leetcode.com/problems/js-event-handling/",
    yt_link: "https://www.youtube.com/watch?v=7U3axjWd4W8",
    article_link: "https://developer.mozilla.org/en-US/docs/Web/Events",
    level: "easy",
  },
  {
    topic: "Web Development",
    task_name: "React Component Basics",
    leetcode_link: "https://leetcode.com/problems/react-components/",
    yt_link: "https://www.youtube.com/watch?v=1rjfH_XH0GE",
    article_link: "https://reactjs.org/docs/components-and-props.html",
    level: "medium",
  },
  {
    topic: "Cloud Computing",
    task_name: "AWS EC2 Instance Setup",
    leetcode_link: "https://leetcode.com/problems/aws-ec2/",
    yt_link: "https://www.youtube.com/watch?v=8TlukLu0tLY",
    article_link:
      "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launching-instance.html",
    level: "medium",
  },
  {
    topic: "Cloud Computing",
    task_name: "Docker Container Basics",
    leetcode_link: "https://leetcode.com/problems/docker-container/",
    yt_link: "https://www.youtube.com/watch?v=YFl2mCHdv24",
    article_link: "https://www.docker.com/resources/what-container",
    level: "medium",
  },
  {
    topic: "Cloud Computing",
    task_name: "Kubernetes Pod Deployment",
    leetcode_link: "https://leetcode.com/problems/kubernetes-pod/",
    yt_link: "https://www.youtube.com/watch?v=s_o8ugFr0j8",
    article_link: "https://kubernetes.io/docs/concepts/workloads/pods/",
    level: "hard",
  },
  {
    topic: "Cloud Computing",
    task_name: "Serverless Function Setup",
    leetcode_link: "https://leetcode.com/problems/serverless-function/",
    yt_link: "https://www.youtube.com/watch?v=5mC1bTsE3kY",
    article_link: "https://aws.amazon.com/lambda/getting-started/",
    level: "hard",
  },
  {
    topic: "Cloud Computing",
    task_name: "Cloud Storage Basics",
    leetcode_link: "https://leetcode.com/problems/cloud-storage/",
    yt_link: "https://www.youtube.com/watch?v=9z4qG_h8QeQ",
    article_link: "https://cloud.google.com/storage/docs/introduction",
    level: "easy",
  },
  {
    topic: "Mathematics",
    task_name: "Matrix Multiplication",
    leetcode_link: "https://leetcode.com/problems/matrix-multiplication/",
    yt_link: "https://www.youtube.com/watch?v=OMA2Mwo0aNg",
    article_link: "https://www.mathsisfun.com/algebra/matrix-multiplying.html",
    level: "medium",
  },
  {
    topic: "Mathematics",
    task_name: "Prime Number Generation",
    leetcode_link: "https://leetcode.com/problems/count-primes/",
    yt_link: "https://www.youtube.com/watch?v=eKp56OLhoQs",
    article_link: "https://www.geeksforgeeks.org/sieve-of-eratosthenes/",
    level: "medium",
  },
  {
    topic: "Mathematics",
    task_name: "Fibonacci Sequence",
    leetcode_link: "https://leetcode.com/problems/fibonacci-number/",
    yt_link: "https://www.youtube.com/watch?v=zg-ddPbzcKM",
    article_link: "https://www.mathsisfun.com/numbers/fibonacci-sequence.html",
    level: "easy",
  },
  {
    topic: "Mathematics",
    task_name: "Graph Theory Basics",
    leetcode_link: "https://leetcode.com/problems/graph-theory/",
    yt_link: "https://www.youtube.com/watch?v=MBT4WGGhDzU",
    article_link:
      "https://www.geeksforgeeks.org/mathematics-graph-theory-basics/",
    level: "hard",
  },
  {
    topic: "Mathematics",
    task_name: "Probability Basics",
    leetcode_link: "https://leetcode.com/problems/probability-basics/",
    yt_link: "https://www.youtube.com/watch?v=uzkc-qNVoOk",
    article_link: "https://www.mathsisfun.com/probability/index.html",
    level: "easy",
  },
];
module.exports = topicData;
